version: '3'

services:

  app:
    image: maven:3-jdk-8
    command: mvn spring-boot:run -Pdev
    working_dir: /usr/app
    volumes:
      - ./:/usr/app
      - m2:/root/.m2
    ports:
      - "8080:8080"
      - "5005:5005"

volumes:
  m2:
